# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2.0.1
_src_path: https://github.com/napari/napari-plugin-template
display_name: etMINFLUX Data Viewer
email: jonatan.alvelid@scilifelab.se
full_name: Jonatan Alvelid
github_repository_url: https://github.com/jonatanalvelid/napari-etminflux-data-viewer
github_username_or_organization: jonatanalvelid
include_reader_plugin: true
include_sample_data_plugin: true
include_widget_plugin: true
include_writer_plugin: false
install_dependabot: true
install_precommit: true
license: GNU GPL v3.0
module_name: napari_etminflux_data_viewer
plugin_name: napari-etminflux-data-viewer
short_description: A napari plugin for viewing overlapping confocal and MINFLUX data
    from etMINFLUX experiments.
